### ISSUE TITLE
Atom complains there are depricated methods and such you are using.

### ISSUE THREAD

**Issue by Gnomorian** [kasima/kobalt#7]
Use the `atom-text-editor` tag instead of the `editor` class.
Use the `atom-text-editor` tag instead of the `editor-colors` class.
Use the selector `atom-text-editor[mini]` to select mini-editors.
Target the selector `:host, atom-text-editor` instead of `.editor` for shadow DOM support.
Target the selector `:host, atom-text-editor` instead of `.editor-colors` for shadow DOM support.

**Comment by kasima** [comment]
Fixed in `0.5.0`
